version: '3'

services:
  postgres:
    image: postgres:12.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: alxmedium-auth
      POSTGRES_PASSWORD: alxmedium-auth-service-password
      POSTGRES_USER: alxmedium-auth-service
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
