version: 2.1

executors:
  node:
    docker:
      - image: node:12.16.1

commands:
  setup_job:
    description: 'Install and set all the required components to run the jobs'
    steps:
      - run:
          name: 'Install Dependencies'
          command: npm i

jobs:
  codacy:
    executor: node
    steps:
      - checkout
      - setup_job
      - run:
          name: 'Codacy'
          command: |
            npm test
            bash <(curl -Ls https://coverage.codacy.com/get.sh)
  codecov:
    executor: node
    steps:
      - checkout
      - setup_job
      - run:
          name: 'CodeCov'
          command: |
            npm test
            cp coverage/coverage-final.json coverage/coverage.json
            bash <(curl -s https://codecov.io/bash)
  lint:
    executor: node
    steps:
      - checkout
      - setup_job
      - run:
          name: 'Run Linter'
          command: npm run lint
  test:
    executor: node
    steps:
      - checkout
      - setup_job
      - run:
          name: 'Run Tests'
          command: npm run test:ci

workflows:
  version: 2

  development:
    jobs:
      - lint:
          filters:
            branches:
              ignore: master
      - test:
          filters:
            branches:
              ignore: master
          requires:
            - lint
      - codecov:
          filters:
            branches:
              ignore: master
          requires:
            - test
      - codacy:
          filters:
            branches:
              ignore: master
          requires:
            - test

  production:
    jobs:
      - lint:
          filters:
            branches:
              only: master
      - test:
          filters:
            branches:
              only: master
          requires:
            - lint
      - codecov:
          filters:
            branches:
              only: master
          requires:
            - test
      - codacy:
          filters:
            branches:
              only: master
          requires:
            - test
